---

- name: Remove PV
  uri:
    url: "{{ kube_nfs_volumes_kubernetes_url }}/api/v1/persistentvolumes/pv-{{ lv_name }}"
    method: DELETE
    status_code: 200
    return_content: yes
    HEADER_Authorization: "Bearer {{ kubernetes_token }}"
    validate_certs: false
  when: delete_PV   
  
- name: Start nfs on Fedora/Red Hat
  systemd:
    name: nfs-server
    state: restarted
    enabled: yes    
    
- name: Unmount logical-volume
  mount:
    name: "/exports/{{ vg_name }}/{{ lv_name }}"
    src: "/dev/{{ vg_name }}/{{ lv_name }}"
    fstype: ext4
    state: unmounted

- name: Remove logical-volume
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    force: yes
    state: absent
